spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

logging:
  level:
    root: info

